server:
  port: 9000
architers:
  object-storage:
    minio:
      enabled: true
      endpoint: http://120.48.170.201:9000
      accessKey: "test"
      secretKey: testtest
      defaultBucket: luyi-dev
  cache:
    redisson:
      config:
        singleServerConfig:
          address: redis://120.48.170.201:6380
          password: 19940825
    default-cache-operate-class: io.github.architers.redisson.cache.support.ValueCacheOperate

spring:
  main:
    allow-circular-references: true
  application:
    name: file-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19940825Ls
    url: jdbc:mysql://120.48.170.201:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  cloud:
    stream:
      rocketmq:
        binder:
          enable-msg-trace: true
          name-server: 120.48.170.201:9876
      bindings:
        storeFileTask-in-0:
          destination: file_task_store
          group: test-group-luyi
          consumer:
            concurrency: 10
            max-attempts: 3
        storeFileTask-out-0:
          destination: file_task_store
        fileTaskResult-in-0:
          destination: file-task-result
          group: file-task-result-group
    function:
      definition: storeFileTask;fileTaskResult
    nacos:
      discovery:
        server-addr: 120.48.170.201:8848
        #group: dev
        namespace: public
        group: DEFAULT_GROUP
        enabled: true
  profiles:
    active: dev
#mybatis-plus:
#  lazy-initialization: true
