server:
  port: 8000

architecture:
  object-storage:
    minio:
      enabled: true
      endpoint: http://120.48.170.201:9000
      accessKey: "test"
      secretKey: testtest
      defaultBucket: luyi-dev
    oss:
      enabled: true
      endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
      accessKey: "66LTAI5tNYseX7zPTFRqQqsExv66"
      secretKey: "66sOQVMVdThQNRwMNpo0hMfxT0QXgmrR66"
      defaultBucket: "0825test"
    cos:
      enabled: true
      endpoint: "https://luyi-dev-1300135689.cos.ap-nanjing.myqcloud.com"
      accessKey: "6AKIDylKdhW6RWMTQ7ZmjRwCDzVllV0GI5cuw6"
      secretKey: "6pOhkX5NSN3UfaIlywgAON6aonW0FEdni6"
      defaultBucket: "luyi-dev-1300135689"
      region: "ap-nanjing"
